version: '3.1'

services:
    mongo:
        image: mongo:latest
        hostname: test_mongodb
        ports:
            - "27017:27017"
        volumes:
            - ./mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
        environment:
            - MONGO_INITDB_DATABASE=weather_db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example

    apicaller:
        build: ./deploy/apicaller
        depends_on:
            - mongo
        ports:
            - 8080:8080
        links:
            - mongo

    dataparser:
        build: ./deploy/dataparser
        ports:
            - 8082:8082

    predictionservice:
        build: ./deploy/predictionservice
        ports:
            - 8083:8083

    visualizerservice:
        build: ./deploy/visualizerservice
        ports:
            - 8084:8084
