services:
    apicaller:
        build: ./apicaller
        ports:
            - 8081:8081

    dataparser:
        build: ./dataparser
        ports:
            - 8082:8082
    
    predictionservice:
        build: ./predictionservice
        ports:
            - 8083:8083

    visualizerservice:
        build:
          context: ./visualizerservice
          dockerfile: Dockerfile
        ports:
            - 8084:8084